name: Docker Build & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları çek
      uses: actions/checkout@v3

    - name: Docker Buildx kur
      uses: docker/setup-buildx-action@v3

    - name: Docker Hub’a giriş yap
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker image oluştur ve push et
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: seninkullaniciadi/seninproje:latest

